-- H2 Local Development Database Setup
-- Car Center Management System - Complete Schema and Data

-- =====================================================
-- 1. 기본 테이블 생성 (H2 네이티브 문법)
-- =====================================================

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid VARCHAR(36) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    role VARCHAR(20) DEFAULT 'CUSTOMER',
    is_active BOOLEAN DEFAULT true,
    email_verified BOOLEAN DEFAULT false,
    last_login_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Vehicle brands table
CREATE TABLE IF NOT EXISTS vehicle_brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    name_en VARCHAR(100) NOT NULL,
    code VARCHAR(10),
    country VARCHAR(50) NOT NULL,
    description TEXT,
    logo_url VARCHAR(255),
    is_active BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Vehicle models table
CREATE TABLE IF NOT EXISTS vehicle_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    name_en VARCHAR(100) NOT NULL,
    code VARCHAR(20),
    category VARCHAR(50),
    start_year INTEGER,
    end_year INTEGER,
    description TEXT,
    image_url VARCHAR(255),
    is_active BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (brand_id) REFERENCES vehicle_brands(id)
);

-- Service types table
CREATE TABLE IF NOT EXISTS service_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    category VARCHAR(50) NOT NULL,
    estimated_duration INTEGER,
    base_price DECIMAL(10,2),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Service centers table
CREATE TABLE IF NOT EXISTS service_centers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    address TEXT NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    email VARCHAR(255),
    average_rating DECIMAL(2,1) DEFAULT 0.0,
    review_count INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    address_detail VARCHAR(100),
    website VARCHAR(255),
    business_number VARCHAR(20) NOT NULL,
    owner_name VARCHAR(50) NOT NULL,
    latitude DOUBLE,
    longitude DOUBLE,
    verification_status VARCHAR(20) DEFAULT 'PENDING',
    verification_date TIMESTAMP,
    is_operating BOOLEAN DEFAULT false,
    specialized_services TEXT,
    facilities TEXT,
    special_notes TEXT,
    image_url VARCHAR(255),
    created_by BIGINT,
    updated_by BIGINT
);

-- Vehicles table
CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_uuid VARCHAR(36) UNIQUE NOT NULL,
    user_id BIGINT NOT NULL,
    make VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    vehicle_year INTEGER NOT NULL,
    license_plate VARCHAR(20) UNIQUE NOT NULL,
    vin VARCHAR(17) UNIQUE,
    engine_type VARCHAR(50),
    fuel_type VARCHAR(20),
    mileage INTEGER DEFAULT 0,
    color VARCHAR(50),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    brand_id BIGINT,
    model_id BIGINT,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (brand_id) REFERENCES vehicle_brands(id),
    FOREIGN KEY (model_id) REFERENCES vehicle_models(id)
);

-- Notification templates table
CREATE TABLE IF NOT EXISTS notification_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_uuid VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(100) NOT NULL,
    channel VARCHAR(50) NOT NULL,
    language VARCHAR(10) NOT NULL DEFAULT 'ko',
    subject VARCHAR(500),
    title_template TEXT,
    content_template TEXT NOT NULL,
    variables TEXT,
    is_active BOOLEAN DEFAULT true,
    version INTEGER DEFAULT 1,
    description TEXT,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Notification settings table
CREATE TABLE IF NOT EXISTS notification_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    sms_enabled BOOLEAN DEFAULT true,
    push_enabled BOOLEAN DEFAULT true,
    email_enabled BOOLEAN DEFAULT true,
    in_app_enabled BOOLEAN DEFAULT true,
    night_mode_enabled BOOLEAN DEFAULT false,
    quiet_start_hour INTEGER DEFAULT 22,
    quiet_end_hour INTEGER DEFAULT 8,
    promotion_enabled BOOLEAN DEFAULT true,
    timezone VARCHAR(50) DEFAULT 'Asia/Seoul',
    language VARCHAR(10) DEFAULT 'ko',
    type_settings TEXT DEFAULT '{}',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- =====================================================
-- 2. 인덱스 생성
-- =====================================================
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_vehicle_brands_name ON vehicle_brands(name);
CREATE INDEX IF NOT EXISTS idx_vehicle_models_brand_id ON vehicle_models(brand_id);
CREATE INDEX IF NOT EXISTS idx_vehicles_user_id ON vehicles(user_id);
CREATE INDEX IF NOT EXISTS idx_vehicles_license_plate ON vehicles(license_plate);
CREATE INDEX IF NOT EXISTS idx_service_centers_is_active ON service_centers(is_active);

-- =====================================================
-- 3. 초기 데이터 삽입
-- =====================================================

-- Vehicle brands data
INSERT INTO vehicle_brands (name, name_en, code, country, description, sort_order) VALUES
('현대', 'Hyundai', 'HYN', '대한민국', '현대자동차', 1),
('기아', 'Kia', 'KIA', '대한민국', '기아자동차', 2),
('BMW', 'BMW', 'BMW', '독일', 'BMW', 3),
('벤츠', 'Mercedes-Benz', 'MBZ', '독일', '메르세데스-벤츠', 4);

-- Vehicle models data
INSERT INTO vehicle_models (brand_id, name, name_en, code, category, start_year, description, sort_order) VALUES
(1, '아반떼', 'Avante', 'AVT', '준중형', 1990, '현대자동차 준중형 세단', 1),
(1, '소나타', 'Sonata', 'SNT', '중형', 1985, '현대자동차 중형 세단', 2),
(2, 'K5', 'K5', 'K5', '중형', 2010, '기아자동차 중형 세단', 1),
(3, '3시리즈', '3 Series', '3S', '중형', 1975, 'BMW 중형 세단', 1),
(4, 'C클래스', 'C-Class', 'C', '중형', 1993, '벤츠 중형 세단', 1);

-- Service types data
INSERT INTO service_types (name, description, category, estimated_duration, base_price, is_active) VALUES
('정기점검', '차량 정기 점검 서비스', '점검', 60, 50000, true),
('오일교환', '엔진오일 교환 서비스', '정비', 30, 80000, true),
('타이어교체', '타이어 교체 서비스', '정비', 45, 300000, true),
('브레이크패드교체', '브레이크 패드 교체 서비스', '정비', 90, 150000, true),
('배터리교체', '차량 배터리 교체 서비스', '정비', 30, 120000, true);

-- Service centers data
INSERT INTO service_centers (
    name, description, address, phone_number, email, 
    business_number, owner_name, latitude, longitude,
    verification_status, is_active, is_operating,
    specialized_services, facilities, address_detail, website
) VALUES 
('현대모터스 강남점', '현대자동차 공식 서비스센터', '서울특별시 강남구 테헤란로 123', '02-1234-5678', 'gangnam@hyundai.com', 
 '123-45-67890', '김현대', 37.5012, 127.0396, 'APPROVED', true, true,
 '현대차 전문정비, 무상점검', '리프트 10대, 대기실, 주차장', '1층', 'https://gangnam.hyundai.com'),
('기아모터스 서초점', '기아자동차 공식 서비스센터', '서울특별시 서초구 강남대로 456', '02-2345-6789', 'seocho@kia.com',
 '234-56-78901', '박기아', 37.4847, 127.0282, 'APPROVED', true, true,
 '기아차 전문정비, 신속정비', '리프트 8대, 고객휴게실', '지하1층', 'https://seocho.kia.com');

-- Test users data
INSERT INTO users (user_uuid, email, password, name, phone, role, is_active, email_verified) VALUES
('550e8400-e29b-41d4-a716-446655440000', 'admin@test.com', '$2a$12$8D7zQaGVF394BaWUF0gKrekUHai8G/Xb.u/yoEo.d3sBJkXyrUJlC', 
 '시스템관리자', '02-1234-5678', 'SYSTEM_ADMIN', true, true),
('550e8400-e29b-41d4-a716-446655440001', 'customer1@test.com', '$2a$12$8D7zQaGVF394BaWUF0gKrekUHai8G/Xb.u/yoEo.d3sBJkXyrUJlC',
 '홍길동', '010-1234-5678', 'CUSTOMER', true, true),
('550e8400-e29b-41d4-a716-446655440002', 'customer2@test.com', '$2a$12$8D7zQaGVF394BaWUF0gKrekUHai8G/Xb.u/yoEo.d3sBJkXyrUJlC',
 '김영희', '010-2345-6789', 'CUSTOMER', true, true);

-- Test vehicles data
INSERT INTO vehicles (vehicle_uuid, user_id, make, model, vehicle_year, license_plate, vin, fuel_type, mileage, color, brand_id, model_id) VALUES
('550e8400-e29b-41d4-a716-446655440030', 2, '현대', '아반떼', 2022, '12가3456', 'KMHL14JA5NA123456', 'GASOLINE', 25000, '흰색', 1, 1),
('550e8400-e29b-41d4-a716-446655440031', 2, '기아', 'K5', 2021, '23나4567', 'KNAG34LA5MA234567', 'GASOLINE', 35000, '검은색', 2, 3),
('550e8400-e29b-41d4-a716-446655440032', 3, 'BMW', '320i', 2020, '34다5678', 'WBA8E5G57LNT12345', 'GASOLINE', 45000, '은색', 3, 4);

-- Notification templates data
INSERT INTO notification_templates (
    template_uuid, name, type, channel, language, subject, title_template, content_template, variables, is_active
) VALUES
('template-reservation-sms', '예약확인_SMS', 'RESERVATION_CONFIRMED', 'SMS', 'ko', NULL,
 '예약이 확인되었습니다', '예약이 확인되었습니다. 예약번호: {{reservationNumber}}',
 '{"reservationNumber": "예약번호"}', true),
('template-payment-sms', '결제완료_SMS', 'PAYMENT_COMPLETED', 'SMS', 'ko', NULL,
 '결제가 완료되었습니다', '결제가 완료되었습니다. 결제번호: {{paymentId}}',
 '{"paymentId": "결제번호"}', true);

-- Notification settings data
INSERT INTO notification_settings (user_id, sms_enabled, push_enabled, email_enabled, in_app_enabled) VALUES
(1, true, true, true, true),  -- admin
(2, true, true, true, true),  -- customer1
(3, true, true, true, true);  -- customer2 