version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    # Ona Agent 연결 문제 방지
    network_mode: host

    # VS Code가 attach 하는 컨테이너의 작업 폴더
    working_dir: /workspace

    volumes:
      - ..:/workspace:cached

    # .env 유무와 상관없이 기본값을 보유(루트 .env가 있으면 자동으로 override 됨)
    environment:
      NEO4J_URI: bolt://localhost:7687
      NEO4J_USERNAME: csauser
      NEO4J_PASSWORD: ${CSAUSER_PASSWORD:-csauser123}
      PYTHONUNBUFFERED: "1"
      PLANTUML_JAR_PATH: /workspace/libs/plantuml.jar
      MMDC_PATH: /usr/local/bin/mmdc
      JAVA_HOME: /usr/lib/jvm/java-21-openjdk-amd64

    # Dev Container attach만 유지(앱 실행은 터미널에서)
    command: bash -lc "sleep infinity"

  neo4j:
    image: neo4j:5
    hostname: neo4j
    restart: unless-stopped
    network_mode: host

    environment:
      # 초기 관리자 암호(임시)
      NEO4J_AUTH: neo4j/neo4j-temp
      # Community: 기본 DB 이름 지정
      NEO4J_dbms_default__database: csadb01
      # 플러그인
      NEO4J_PLUGINS: "apoc,gds"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
      # 메모리
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 1g
      # Gitpod 외부 접속을 위한 설정
      NEO4J_server_bolt_advertised__address: :7687
      NEO4J_server_http_advertised__address: :7474
      NEO4J_dbms_connector_bolt_listen__address: 0.0.0.0:7687
      NEO4J_dbms_connector_http_listen__address: 0.0.0.0:7474

    volumes:
      - ../neo4j/data:/data
      - ../neo4j/import:/import
      - ../neo4j/plugins:/plugins

    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "neo4j-temp", "RETURN 1;"]
      interval: 5s
      timeout: 3s
      retries: 30

  neo4j-init:
    image: neo4j:5
    depends_on:
      neo4j:
        condition: service_healthy
    network_mode: host

    environment:
      # .env 없을 때도 기본값으로 기동되도록
      CSAUSER_PASSWORD: ${CSAUSER_PASSWORD:-csauser123}

    volumes:
      - ../neo4j/init.system.cypher:/init.system.cypher:ro

    entrypoint: ["/bin/bash", "-lc"]
    command: >
      "
      set -e
      echo '[init] Creating csauser in system DB...'
      cypher-shell -u neo4j -p neo4j-temp -d system -f /init.system.cypher
      echo '[init] Neo4j user init done ✅'
      "