app:
  build:
    context: ..
    dockerfile: .devcontainer/Dockerfile
  working_dir: /workspace
  volumes:
    - ..:/workspace:cached
  depends_on:
    neo4j:
      condition: service_healthy
  environment:
    NEO4J_URI: bolt://neo4j:7687
    NEO4J_USERNAME: csauser
    NEO4J_PASSWORD: ${CSAUSER_PASSWORD}
    PYTHONUNBUFFERED: "1"
    # 수정된 PlantUML 경로 반영
    PLANTUML_JAR_PATH: /workspace/lang-java-springboot/libs/plantuml.jar
    MMDC_PATH: /usr/local/bin/mmdc
  #command: bash -lc "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
  ports:
    - "13000:13000"

